version: '3'

services:
  sim:
    image: us-west1-docker.pkg.dev/namaph-namaph-dev/instant-repo/sim:latest
    container_name: "namaph-sim"
    hostname: "namaph-sim"
    environment:
      - LOCAL=local
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/app/secrets/namaph.json
    ports:
      - "8000:8000"
    volumes:
      - ./secrets:/opt/app/secrets