version: '3'

services:
  redis:
    image: redis:latest
    container_name: "namaph-redis"
    hostname: "namaph-redis"
    ports:
      - "6379:6379"
    volumes:
      - "./sample/redis:/data"
  sim:
    image: us-west1-docker.pkg.dev/namaph-namaph-dev/instant-repo/sim:latest
    container_name: "namaph-sim"
    hostname: "namaph-sim"
    environment:
      - LOCAL=local
      - REDISHOST=namaph-redis
      - REDISPORT=6379
    ports:
      - "8000:8000"